USE CarSolution360
CREATE TABLE Car( 
	IdCar INT IDENTITY (1,1) NOT NULL,
	Brand VARCHAR(25) NOT NULL,
	Color VARCHAR(20) NOT NULL,
	Model VARCHAR(20) NOT NULL,
	PriceSale DECIMAL NOT NULL,
	CONSTRAINT PK_IdCar PRIMARY KEY CLUSTERED (IdCar)
)


